### ISSUE TITLE
Brother Toner Cartridges not detected

### ISSUE THREAD

**Issue by Napsty** [lausser/check_printer_health#2]
Hi Gerhard,

Just did some quick testing on check_printer_health and noticed that on a Brother MFC-9330CDW the `supplies-status` check does not include the toner cartridges. On the other hand the drum units are covered:

```
$ ./check_printer_health --hostname xxx.xxx.xxx.xxx --mode supplies-status
OK - supplies status is fine | 'Yellow_Drum_Unit_remaining'=72.15%;20:;5:;0;100 'Belt_Unit_remaining'=68.51%;20:;5:;0;100 'Black_Drum_Unit_remaining'=72.15%;20:;5:;0;100 'Cyan_Drum_Unit_remaining'=39.72%;20:;5:;0;100 'Magenta_Drum_Unit_remaining'=39.72%;20:;5:;0;100
```

Snmpwalk shows:

```
[...]
.1.3.6.1.2.1.43.11.1.1.6.1.1 = STRING: "Black Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.2 = STRING: "Cyan Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.3 = STRING: "Magenta Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.4 = STRING: "Yellow Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.5 = STRING: "Waste Toner Box"
.1.3.6.1.2.1.43.11.1.1.6.1.6 = STRING: "Belt Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.7 = STRING: "Black Drum Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.8 = STRING: "Cyan Drum Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.9 = STRING: "Magenta Drum Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.10 = STRING: "Yellow Drum Unit"
[...]
```

The black toner is low on ink and should alert. 

Maybe I get a chance to look at it further, but for now I just leave this information. If you want the snmpwalk output, let me know.

**Comment by lausser** [comment]
Hi Claudio,

run .... --mode walk  and pipe the output in a shell. This results in a snmpwalk-file, which i can use to simulate your printer. (when i find the time )

Gerhard
________________________________
From: Claudio Kuenzler ***@***.***>
Sent: Tuesday, June 11, 2024 9:33 AM
To: lausser/check_printer_health ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lausser/check_printer_health] Brother Toner Cartridges not detected (Issue #2)


Hi Gerhard,

Just did some quick testing on check_printer_health and noticed that on a Brother MFC-9330CDW the supplies-status check does not include the toner cartridges. On the other hand the drum units are covered:

$ ./check_printer_health --hostname xxx.xxx.xxx.xxx --mode supplies-status
OK - supplies status is fine | 'Yellow_Drum_Unit_remaining'=72.15%;20:;5:;0;100 'Belt_Unit_remaining'=68.51%;20:;5:;0;100 'Black_Drum_Unit_remaining'=72.15%;20:;5:;0;100 'Cyan_Drum_Unit_remaining'=39.72%;20:;5:;0;100 'Magenta_Drum_Unit_remaining'=39.72%;20:;5:;0;100


Snmpwalk shows:

[...]
.1.3.6.1.2.1.43.11.1.1.6.1.1 = STRING: "Black Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.2 = STRING: "Cyan Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.3 = STRING: "Magenta Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.4 = STRING: "Yellow Toner Cartridge"
.1.3.6.1.2.1.43.11.1.1.6.1.5 = STRING: "Waste Toner Box"
.1.3.6.1.2.1.43.11.1.1.6.1.6 = STRING: "Belt Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.7 = STRING: "Black Drum Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.8 = STRING: "Cyan Drum Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.9 = STRING: "Magenta Drum Unit"
.1.3.6.1.2.1.43.11.1.1.6.1.10 = STRING: "Yellow Drum Unit"
[...]


The black toner is low on ink and should alert.

Maybe I get a chance to look at it further, but for now I just leave this information. If you want the snmpwalk output, let me know.

**Comment by lausser** [comment]
Printer-MIB says:
```
prtMarkerSuppliesLevel OBJECT-TYPE
    SYNTAX     Integer32
    MAX-ACCESS read-write
    STATUS     current
    DESCRIPTION
         "The current level if this supply is a container;
         remaining space if this supply is a receptacle. If this
         supply container/receptacle can reliably sense this
         value, the value is reported by the printer and is read-
         only; otherwise, the value may be written (by a Remote
         Control Panel or a Management Application). The value (-
         1) means other and specifically indicates that the sub-
         unit places no restrictions on this parameter. The value
         (-2) means unknown.  A value of (-3) means that the
         printer knows that there is some supply/remaining space,
         respectively."

```

Your printer shows these OID values:
```
[MARKERSUPPLY_1.1]
prtMarkerSuppliesClass: supplyThatIsConsumed
prtMarkerSuppliesColorantIndex: 1
prtMarkerSuppliesDescription: Black Toner Cartridge
prtMarkerSuppliesLevel: -3  <--- unknown level, but the printer thinks it's sufficient
prtMarkerSuppliesMarkerIndex: 1
prtMarkerSuppliesMaxCapacity: -2
prtMarkerSuppliesSupplyUnit: tenthsOfGrams
prtMarkerSuppliesType: toner
usage: 150 <- (this is because is calculates with MaxCapacity and SuppliesLevel. usage is not used later)
info: Black Toner Cartridge is sufficiently large

[MARKERSUPPLY_1.10]
prtMarkerSuppliesClass: supplyThatIsConsumed
prtMarkerSuppliesColorantIndex: 0
prtMarkerSuppliesDescription: Yellow Drum Unit
prtMarkerSuppliesLevel: 10823
prtMarkerSuppliesMarkerIndex: 1
prtMarkerSuppliesMaxCapacity: 15000
prtMarkerSuppliesSupplyUnit: impressions
prtMarkerSuppliesType: opc
usage: 72.1533333333333
info: Yellow Drum Unit is at 72.15%

```


So in fact, the only information we have on the remaining toner supply is "relax, it's not empty yet" according to the printer itself. That's why there is still an OK status.

**Comment by Napsty** [comment]
thx, appreciate the verification!

**Comment by Napsty** [comment]
However it would be great if the plugin could check for the prtAlertDescription (OID 1.3.6.1.2.1.43.18.1.1.8) and if not null/empty, take the string and exit warning.

Here's the full prtAlert table:

```
.1.3.6.1.2.1.43.18.1.1.2.1.1 = INTEGER: 4
.1.3.6.1.2.1.43.18.1.1.2.1.2 = INTEGER: 0
.1.3.6.1.2.1.43.18.1.1.3.1.1 = INTEGER: 4
.1.3.6.1.2.1.43.18.1.1.3.1.2 = INTEGER: 0
.1.3.6.1.2.1.43.18.1.1.4.1.1 = INTEGER: 11
.1.3.6.1.2.1.43.18.1.1.4.1.2 = INTEGER: 0
.1.3.6.1.2.1.43.18.1.1.5.1.1 = INTEGER: 1
.1.3.6.1.2.1.43.18.1.1.5.1.2 = INTEGER: 0
.1.3.6.1.2.1.43.18.1.1.6.1.1 = INTEGER: 10209
.1.3.6.1.2.1.43.18.1.1.6.1.2 = INTEGER: 40000
.1.3.6.1.2.1.43.18.1.1.7.1.1 = INTEGER: 1104
.1.3.6.1.2.1.43.18.1.1.7.1.2 = INTEGER: 0
.1.3.6.1.2.1.43.18.1.1.8.1.1 = STRING: "Toner Low: BK"
.1.3.6.1.2.1.43.18.1.1.8.1.2 = STRING: "Sleep"
.1.3.6.1.2.1.43.18.1.1.9.1.1 = 0
.1.3.6.1.2.1.43.18.1.1.9.1.2 = 0
```

Edit: created #3

**Comment by gelof2022** [comment]
> Hi Gerhard,
> 
> Just did some quick testing on check_printer_health and noticed that on a Brother MFC-9330CDW the `supplies-status` check does not include the toner cartridges. On the other hand the drum units are covered:
> 
> ```
> $ ./check_printer_health --hostname xxx.xxx.xxx.xxx --mode supplies-status
> OK - supplies status is fine | 'Yellow_Drum_Unit_remaining'=72.15%;20:;5:;0;100 'Belt_Unit_remaining'=68.51%;20:;5:;0;100 'Black_Drum_Unit_remaining'=72.15%;20:;5:;0;100 'Cyan_Drum_Unit_remaining'=39.72%;20:;5:;0;100 'Magenta_Drum_Unit_remaining'=39.72%;20:;5:;0;100
> ```
> 
> Snmpwalk shows:
> 
> ```
> [...]
> .1.3.6.1.2.1.43.11.1.1.6.1.1 = STRING: "Black Toner Cartridge"
> .1.3.6.1.2.1.43.11.1.1.6.1.2 = STRING: "Cyan Toner Cartridge"
> .1.3.6.1.2.1.43.11.1.1.6.1.3 = STRING: "Magenta Toner Cartridge"
> .1.3.6.1.2.1.43.11.1.1.6.1.4 = STRING: "Yellow Toner Cartridge"
> .1.3.6.1.2.1.43.11.1.1.6.1.5 = STRING: "Waste Toner Box"
> .1.3.6.1.2.1.43.11.1.1.6.1.6 = STRING: "Belt Unit"
> .1.3.6.1.2.1.43.11.1.1.6.1.7 = STRING: "Black Drum Unit"
> .1.3.6.1.2.1.43.11.1.1.6.1.8 = STRING: "Cyan Drum Unit"
> .1.3.6.1.2.1.43.11.1.1.6.1.9 = STRING: "Magenta Drum Unit"
> .1.3.6.1.2.1.43.11.1.1.6.1.10 = STRING: "Yellow Drum Unit"
> [...]
> ```
> 
> The black toner is low on ink and should alert.
> 
> Maybe I get a chance to look at it further, but for now I just leave this information. If you want the snmpwalk output, let me know.

If you still needs this this article helps: https://tsmidwest.com/tech-tuesday-brother-printers-snmp/

Below is the template Gemini build me: <?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>6.0</version>
    <date>2025-12-29T22:00:00Z</date>
    <groups>
        <group>
            <uuid>5c6f85d26364421aa6f4c39054790099</uuid>
            <name>Templates/Brother_Secret_Final</name>
        </group>
    </groups>
    <templates>
        <template>
            <uuid>1e739985223348169996618485210099</uuid>
            <template>Template Brother MFC-9330CDW Real Levels</template>
            <name>Template Brother MFC-9330CDW Real Levels</name>
            <description>Monitors exact toner percentages by decoding the Brother 'Maintenance' Hex String. Also monitors Page Counts.
            
            Uses OID: .1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.8.0
            Decodes IDs: 81 (Black), 82 (Cyan), 83 (Magenta), 84 (Yellow)</description>
            <groups>
                <group>
                    <name>Templates/Brother_Secret_Final</name>
                </group>
            </groups>
            <items>
                <item>
                    <uuid>2a849985223348169996618485210080</uuid>
                    <name>Brother Maintenance Data (Raw)</name>
                    <type>SNMP_AGENT</type>
                    <snmp_oid>.1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.8.0</snmp_oid>
                    <key>brother.maintenance.raw</key>
                    <delay>1h</delay>
                    <history>0</history>
                    <trends>0</trends>
                    <value_type>TEXT</value_type>
                    <description>Fetches the raw hex string containing all toner levels.</description>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Raw Data</value>
                        </tag>
                    </tags>
                </item>

                <item>
                    <uuid>2a849985223348169996618485210081</uuid>
                    <name>Black Toner Level</name>
                    <type>DEPENDENT</type>
                    <key>toner.level.black</key>
                    <delay>0</delay>
                    <history>7d</history>
                    <value_type>FLOAT</value_type>
                    <units>%</units>
                    <master_item>
                        <key>brother.maintenance.raw</key>
                    </master_item>
                    <preprocessing>
                        <step>
                            <type>JAVASCRIPT</type>
                            <parameters>
                                <parameter>
                                    // Remove spaces from Hex String
                                    var clean = value.replace(/\s+/g, '');
                                    // Find ID 81 (Black) followed by 01 04 and grab the value 3 bytes later
                                    // Pattern: 81 01 04 [00] [00] [00] [VAL]
                                    var match = clean.match(/810104.{6}([0-9A-Fa-f]{2})/);
                                    return match ? parseInt(match[1], 16) : -1;
                                </parameter>
                            </parameters>
                        </step>
                    </preprocessing>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Consumables</value>
                        </tag>
                    </tags>
                    <triggers>
                        <trigger>
                            <uuid>3b949985223348169996618485210081</uuid>
                            <expression>last(/Template Brother MFC-9330CDW Real Levels/toner.level.black)&lt;10</expression>
                            <name>Black Toner Low (&lt;10%)</name>
                            <priority>WARNING</priority>
                        </trigger>
                    </triggers>
                </item>

                <item>
                    <uuid>2a849985223348169996618485210082</uuid>
                    <name>Cyan Toner Level</name>
                    <type>DEPENDENT</type>
                    <key>toner.level.cyan</key>
                    <delay>0</delay>
                    <history>7d</history>
                    <value_type>FLOAT</value_type>
                    <units>%</units>
                    <master_item>
                        <key>brother.maintenance.raw</key>
                    </master_item>
                    <preprocessing>
                        <step>
                            <type>JAVASCRIPT</type>
                            <parameters>
                                <parameter>
                                    var clean = value.replace(/\s+/g, '');
                                    // ID 82 is Cyan
                                    var match = clean.match(/820104.{6}([0-9A-Fa-f]{2})/);
                                    return match ? parseInt(match[1], 16) : -1;
                                </parameter>
                            </parameters>
                        </step>
                    </preprocessing>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Consumables</value>
                        </tag>
                    </tags>
                    <triggers>
                        <trigger>
                            <uuid>3b949985223348169996618485210082</uuid>
                            <expression>last(/Template Brother MFC-9330CDW Real Levels/toner.level.cyan)&lt;10</expression>
                            <name>Cyan Toner Low (&lt;10%)</name>
                            <priority>WARNING</priority>
                        </trigger>
                    </triggers>
                </item>

                <item>
                    <uuid>2a849985223348169996618485210083</uuid>
                    <name>Magenta Toner Level</name>
                    <type>DEPENDENT</type>
                    <key>toner.level.magenta</key>
                    <delay>0</delay>
                    <history>7d</history>
                    <value_type>FLOAT</value_type>
                    <units>%</units>
                    <master_item>
                        <key>brother.maintenance.raw</key>
                    </master_item>
                    <preprocessing>
                        <step>
                            <type>JAVASCRIPT</type>
                            <parameters>
                                <parameter>
                                    var clean = value.replace(/\s+/g, '');
                                    // ID 83 is Magenta
                                    var match = clean.match(/830104.{6}([0-9A-Fa-f]{2})/);
                                    return match ? parseInt(match[1], 16) : -1;
                                </parameter>
                            </parameters>
                        </step>
                    </preprocessing>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Consumables</value>
                        </tag>
                    </tags>
                    <triggers>
                        <trigger>
                            <uuid>3b949985223348169996618485210083</uuid>
                            <expression>last(/Template Brother MFC-9330CDW Real Levels/toner.level.magenta)&lt;10</expression>
                            <name>Magenta Toner Low (&lt;10%)</name>
                            <priority>WARNING</priority>
                        </trigger>
                    </triggers>
                </item>

                <item>
                    <uuid>2a849985223348169996618485210084</uuid>
                    <name>Yellow Toner Level</name>
                    <type>DEPENDENT</type>
                    <key>toner.level.yellow</key>
                    <delay>0</delay>
                    <history>7d</history>
                    <value_type>FLOAT</value_type>
                    <units>%</units>
                    <master_item>
                        <key>brother.maintenance.raw</key>
                    </master_item>
                    <preprocessing>
                        <step>
                            <type>JAVASCRIPT</type>
                            <parameters>
                                <parameter>
                                    var clean = value.replace(/\s+/g, '');
                                    // ID 84 is Yellow
                                    var match = clean.match(/840104.{6}([0-9A-Fa-f]{2})/);
                                    return match ? parseInt(match[1], 16) : -1;
                                </parameter>
                            </parameters>
                        </step>
                    </preprocessing>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Consumables</value>
                        </tag>
                    </tags>
                    <triggers>
                        <trigger>
                            <uuid>3b949985223348169996618485210084</uuid>
                            <expression>last(/Template Brother MFC-9330CDW Real Levels/toner.level.yellow)&lt;10</expression>
                            <name>Yellow Toner Low (&lt;10%)</name>
                            <priority>WARNING</priority>
                        </trigger>
                    </triggers>
                </item>

                <item>
                    <uuid>2a849985223348169996618485210090</uuid>
                    <name>Total Page Count</name>
                    <type>SNMP_AGENT</type>
                    <snmp_oid>.1.3.6.1.2.1.43.10.2.1.4.1.1</snmp_oid>
                    <key>printer.page.count</key>
                    <delay>1h</delay>
                    <history>30d</history>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Statistics</value>
                        </tag>
                    </tags>
                </item>
                <item>
                    <uuid>2a849985223348169996618485210091</uuid>
                    <name>Pages Printed (Since Power On)</name>
                    <type>SNMP_AGENT</type>
                    <snmp_oid>.1.3.6.1.2.1.43.10.2.1.5.1.1</snmp_oid>
                    <key>printer.page.count.session</key>
                    <delay>15m</delay>
                    <history>7d</history>
                    <description>The number of pages printed since the device was last powered on.</description>
                    <tags>
                        <tag>
                            <tag>Application</tag>
                            <value>Statistics</value>
                        </tag>
                    </tags>
                </item>
            </items>
            <macros>
                <macro>
                    <macro>{$SNMP_COMMUNITY}</macro>
                    <value>public</value>
                </macro>
            </macros>
        </template>
    </templates>
</zabbix_export>
