### ISSUE TITLE
False positives with Alerts in hardware-health

### ISSUE THREAD

**Issue by evilcorp92** [lausser/check_printer_health#4]
With some printers (Kyocera for example) there are a lot of false positives after the addition of Alerts to hardware-health:
![image](https://github.com/user-attachments/assets/99221561-cc41-43b2-a360-506223c3051b)

snmpwalk for debugging:
![image](https://github.com/user-attachments/assets/656c1e9c-ba45-46ad-b7d3-d283834b7d00)

as you can see, the description oid is empty, so the !~ /toner/i won't get rid of those.

please let me know if you need something else.

**Comment by lausser** [comment]
Hi, i need an snmp dump in order to simulate your printer.
Please run 
check_printer_health ..... --mode walk | sh
It creates an snmpwalk-file in /tmp. Send it to gerhard.lausser@consol.de and i have a look.

**Comment by lausser** [comment]
I just pushed release 1.2.0.1 (will also be in tomorrow's OMD)
It ignores alerts which have an empty description. These seem to be events which ahve been sent as traps (like poweredOn) and don't persist.
